<a href="https://colab.research.google.com/github/bangse94/StudyDL/blob/main/Pytorch_tutorial_1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pytorch tutorial

1.  Tensor

- 텐서는 배열이나 행렬과 매우 유사한 특수한 자류구조.
- PyTorch에서는 텐서를 사용하여 모델의 입력과 출력, 그리고 모델의 매개변수들을 부호화(encode)
- 텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 Numpy의 ndarray와 유사
- 텐서와 NumPy 배열은 동일한 내부 메모리를 공유할 수 있어 데이터를 복수할 필요가 없다.
- 텐서는 또한 자동미분에 최적화

In [1]:
import torch
import numpy as np

텐서 초기화
1. 데이터로부터 직접 생성하기
  - 데이터로부터 직접 텐서를 생성 할 수 있다. -> 데이터의 자료형은 자동으로 유추 

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(type(x_data))

<class 'torch.Tensor'>


  2. NumPy 배열로부터 생성하기
    - 텐서는 NumPy 배열로 생성할 수 있다. -> 반대도 가능

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(type(x_np))

<class 'torch.Tensor'>


  3. 다른 텐서로부터 생성하기
    - 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(shape, datatype)을 유지

In [4]:
x_ones = torch.ones_like(x_data)    # x_data의 속성을 유지
print(f"Ones Tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)     # x_data의 속성을 덮어쓴다
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1243, 0.4149],
        [0.3934, 0.1507]]) 



  4. 무작위 또는 상수 값을 사용하기
    - shape는 텐서의 차원(Dimension)을 나타내는 튜플(tuple)

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.2528, 0.9861, 0.6449],
        [0.3069, 0.7372, 0.3017]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



텐서의 속성
  - 텐서의 속성은 텐서의 shape, datatype 및 어느 장치에 저장되는지를 나타낸다

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is sotred on : {tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is sotred on : cpu


텐서 연산
  - transposing, indexing, slicing, 수학 계산, 선형 대수, random sampling등 다양한 연산 제공
  - 각 연산들은 GPU에서 실행 가능
  - 기본적으로 텐서는 cpu에 생성 -> .to 메소드를 사용하면 GPU로 텐서를 명시적으로 이용가능

In [7]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(tensor.device)

cuda:0


  1. NumPy식의 표준 인덱싱과 슬라이싱

In [8]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


  2. 텐서 합치기
    - torch.cat 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결 할 수 있다. -> torch.cat과 미묘하게 다른 텐서 결합 연산인 torch.stack도 있다.

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


  3. 산술 연산

In [13]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산한다. y1, y2, y3는 모두 같은 값을 갖는다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
print(f"{y1} \n {y2} \n {y3}")
print(torch.matmul(tensor, tensor.T, out=y3))


# 요소 곱(element-wise product)을 계산한다. z1, z2, z3는 모두 같은 값을 갖는다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
print(f"{z1} \n {z2} \n {z3}")
print(torch.mul(tensor, tensor, out=z3))

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 
 tensor([[0.0429, 0.7747, 0.9185, 0.8935],
        [0.6892, 0.5887, 0.5079, 0.3342],
        [0.3961, 0.1755, 0.0045, 0.7419],
        [0.7416, 0.1248, 0.6503, 0.2916]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[0.1507, 0.9901, 0.9583, 0.1631],
        [0.8323, 0.7954, 0.7755, 0.6821],
        [0.2005, 0.7550, 0.4575, 0.6571],
        [0.5833, 0.5131, 0.9384, 0.0341]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


  4. 단일 요소 텐서
    - 텐서의 모든 값을 하나로 집계(aggregate)하여 요소하 하나인 텐서의 경우 item()을 사용하여 Python 숫자 값으로 변환 할 수 있다

In [14]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


  5. 바꿔치기 연산
    - 연산 결과를 피연산자에 저장하는 연산을 in-place 연산이라고 부르며, _ 접미사를 갖는다. 
    - ex) x.copy_(y) 나 x.t_()는 x를 변경

    - in-place 연산은 메모리를 일부 절약하지만, history가 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생 할 수 있다. -> 사용을 권장하지 않음

In [15]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


NumPy 변환
  - CPU상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

  1. 텐서를 Numpy 배열로 변환하기

In [16]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [17]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


  2. NumPy 배열을 텐서로 변환하기

In [18]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
